name: Release

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_SECRET }} 
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package & Release
        uses: BigWigsMods/packager@v2
        with:
          args: -p curseforge -p github
          pandoc: true
