name: Release

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      TAG: v${{ github.run_number }}
      ZIP: FuldFokusEmotes-v${{ github.run_number }}.zip
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build zip
        run: |
          mkdir -p dist/FuldFokusEmotes
          cp -r Emotes dist/FuldFokusEmotes/
          cp -r UI dist/FuldFokusEmotes/
          cp FuldFokusEmotes.lua dist/FuldFokusEmotes/
          cp FuldFokusEmotes.toc dist/FuldFokusEmotes/
          cd dist
          zip -r "$ZIP" FuldFokusEmotes

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG $GITHUB_SHA
          git push origin $TAG

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          files: dist/${{ env.ZIP }}
          generate_release_notes: true

      - name: Publish to CurseForge/Wago
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
